FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  git \
  python3-cryptography \
  wget \
  && rm -rf /var/lib/apt/lists/*

RUN git clone --branch scarthgap https://github.com/OE4T/meta-tegra.git meta-tegra-scarthgap

RUN mkdir -p /opt/nvidia/L4T-36.4.4-tegra234

RUN wget -q -O /opt/nvidia/l4t-release.tbz2 https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.3/release/Jetson_Linux_R36.4.4_aarch64.tbz2

RUN tar -xjf /opt/nvidia/l4t-release.tbz2 -C /opt/nvidia/L4T-36.4.4-tegra234

RUN rm /opt/nvidia/l4t-release.tbz2

RUN wget -q -O /opt/nvidia/public_sources.tbz2 https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.3/sources/public_sources.tbz2

RUN tar -xjf /opt/nvidia/public_sources.tbz2 -C /opt/nvidia/L4T-36.4.4-tegra234 Linux_for_Tegra/source/nvidia-jetson-optee-source.tbz2 && \
    mkdir /opt/nvidia/L4T-36.4.4-tegra234/Linux_for_Tegra/source/public && \
    tar -xjf /opt/nvidia/L4T-36.4.4-tegra234/Linux_for_Tegra/source/nvidia-jetson-optee-source.tbz2 -C /opt/nvidia/L4T-36.4.4-tegra234/Linux_for_Tegra/source/public

RUN rm /opt/nvidia/public_sources.tbz2 && \
    rm /opt/nvidia/L4T-36.4.4-tegra234/Linux_for_Tegra/source/nvidia-jetson-optee-source.tbz2

ARG TEGRA234_36_4_4_DIR=/opt/nvidia/L4T-36.4.4-tegra234/Linux_for_Tegra

RUN cd meta-tegra-scarthgap/recipes-bsp/tegra-binaries/tegra-helper-scripts && \
    install -m 0755 tegra-flash-helper.sh ${TEGRA234_36_4_4_DIR}/bootloader/tegra234-flash-helper && \
    install -m 0755 tegra-signimage-helper.sh ${TEGRA234_36_4_4_DIR}/tegra-signimage-helper && \
    install -m 0755 nvflashxmlparse.py ${TEGRA234_36_4_4_DIR}/bootloader/nvflashxmlparse

RUN patch -p1 --directory=${TEGRA234_36_4_4_DIR} < meta-tegra-scarthgap/recipes-bsp/tegra-binaries/files/0013-Fix-location-of-bsp_version-file-in-l4t_bup_gen.func.patch
