FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  git \
  wget \
  && rm -rf /var/lib/apt/lists/*

# digsigserver utilizes a helper script which is only available in later
# versions of the dunfell branch
RUN git clone --branch dunfell https://github.com/OE4T/meta-tegra.git meta-tegra-dunfell

RUN mkdir -p /opt/nvidia/L4T-32.5.2-tegra210
RUN wget -q -O - https://developer.download.nvidia.com/embedded/L4T/r32_Release_v5.2/T210/Jetson-210_Linux_R32.5.2_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-32.5.2-tegra210
RUN wget -q -O - https://developer.download.nvidia.com/embedded/L4T/r32_Release_v5.2/T210/secureboot_R32.5.2_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-32.5.2-tegra210

RUN mkdir -p /opt/nvidia/L4T-32.5.2-tegra186
RUN wget -q -O - https://developer.download.nvidia.com/embedded/L4T/r32_Release_v5.2/T186/Jetson_Linux_R32.5.2_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-32.5.2-tegra186
RUN wget -q -O - https://developer.download.nvidia.com/embedded/L4T/r32_Release_v5.2/T186/secureboot_R32.5.2_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-32.5.2-tegra186

RUN git clone --branch dunfell-l4t-r32.5.0 https://github.com/OE4T/meta-tegra.git meta-tegra-dunfell-l4t-r32.5.0

ARG TEGRA210_32_5_2_DIR=/opt/nvidia/L4T-32.5.2-tegra210/Linux_for_Tegra
ARG TEGRA186_32_5_2_DIR=/opt/nvidia/L4T-32.5.2-tegra186/Linux_for_Tegra

RUN cd meta-tegra-dunfell-l4t-r32.5.0/recipes-bsp/tegra-binaries/tegra-helper-scripts && \
    install -m 0755 tegra210-flash-helper.sh ${TEGRA210_32_5_2_DIR}/bootloader/tegra210-flash-helper && \
    install -m 0755 tegra194-flash-helper.sh ${TEGRA186_32_5_2_DIR}/bootloader/tegra194-flash-helper && \
    install -m 0755 nvflashxmlparse.py ${TEGRA210_32_5_2_DIR}/bootloader/nvflashxmlparse

RUN cd meta-tegra-dunfell/recipes-bsp/tegra-binaries/tegra-helper-scripts && \
    install -m 0755 tegra-signimage-helper.sh ${TEGRA210_32_5_2_DIR}/tegra-signimage-helper && \
    install -m 0755 tegra-signimage-helper.sh ${TEGRA186_32_5_2_DIR}/tegra-signimage-helper

RUN patch -p1 --directory=${TEGRA210_32_5_2_DIR} < meta-tegra-dunfell-l4t-r32.5.0/recipes-bsp/tegra-binaries/files/0002-Fix-typo-in-l4t_bup_gen.func.patch
RUN patch -p1 --directory=${TEGRA186_32_5_2_DIR} < meta-tegra-dunfell-l4t-r32.5.0/recipes-bsp/tegra-binaries/files/0002-Fix-typo-in-l4t_bup_gen.func.patch
RUN patch -p1 --directory=${TEGRA210_32_5_2_DIR} < meta-tegra-dunfell-l4t-r32.5.0/recipes-bsp/tegra-binaries/files/0008-Skip-qspi-sd-specific-entries-for-other-t210-BUP-pay.patch
