FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  git \
  wget \
  && rm -rf /var/lib/apt/lists/*

RUN git clone --branch dunfell https://github.com/OE4T/meta-tegra.git meta-tegra-dunfell

RUN mkdir -p /opt/nvidia/L4T-32.7.4-tegra210
RUN wget -q -O - https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.4/t210/jetson-210_linux_r32.7.4_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-32.7.4-tegra210
RUN wget -q -O - https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.4/t210/secureboot_r32.7.4_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-32.7.4-tegra210

RUN mkdir -p /opt/nvidia/L4T-32.7.4-tegra186
RUN wget -q -O - https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.4/t186/jetson_linux_r32.7.4_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-32.7.4-tegra186
RUN wget -q -O - https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.4/t186/secureboot_r32.7.4_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-32.7.4-tegra186

ARG TEGRA210_32_7_4_DIR=/opt/nvidia/L4T-32.7.4-tegra210/Linux_for_Tegra
ARG TEGRA186_32_7_4_DIR=/opt/nvidia/L4T-32.7.4-tegra186/Linux_for_Tegra

RUN cd meta-tegra-dunfell/recipes-bsp/tegra-binaries/tegra-helper-scripts && \
    install -m 0755 tegra210-flash-helper.sh ${TEGRA210_32_7_4_DIR}/bootloader/tegra210-flash-helper && \
    install -m 0755 tegra194-flash-helper.sh ${TEGRA186_32_7_4_DIR}/bootloader/tegra194-flash-helper && \
    install -m 0755 tegra-signimage-helper.sh ${TEGRA210_32_7_4_DIR}/tegra-signimage-helper && \
    install -m 0755 tegra-signimage-helper.sh ${TEGRA186_32_7_4_DIR}/tegra-signimage-helper && \
    install -m 0755 nvflashxmlparse.py ${TEGRA210_32_7_4_DIR}/bootloader/nvflashxmlparse

RUN patch -p1 --directory=${TEGRA210_32_7_4_DIR} < meta-tegra-dunfell/recipes-bsp/tegra-binaries/files/0013-Fix-location-of-bsp_version-file-in-l4t_bup_gen.func.patch
RUN patch -p1 --directory=${TEGRA186_32_7_4_DIR} < meta-tegra-dunfell/recipes-bsp/tegra-binaries/files/0013-Fix-location-of-bsp_version-file-in-l4t_bup_gen.func.patch
