FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  git \
  wget \
  && rm -rf /var/lib/apt/lists/*

RUN git clone --branch kirkstone https://github.com/OE4T/meta-tegra.git meta-tegra-kirkstone

RUN mkdir -p /opt/nvidia/L4T-35.4.1-tegra234
RUN wget -q -O - https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v4.1/release/jetson_linux_r35.4.1_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-35.4.1-tegra234

RUN mkdir -p /opt/nvidia/L4T-35.4.1-tegra186
RUN wget -q -O - https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v4.1/release/jetson_linux_r35.4.1_aarch64.tbz2 | \
    tar -xjf - -C /opt/nvidia/L4T-35.4.1-tegra186

ARG TEGRA234_35_4_1_DIR=/opt/nvidia/L4T-35.4.1-tegra234/Linux_for_Tegra
ARG TEGRA186_35_4_1_DIR=/opt/nvidia/L4T-35.4.1-tegra186/Linux_for_Tegra

RUN cd meta-tegra-kirkstone/recipes-bsp/tegra-binaries/tegra-helper-scripts && \
    install -m 0755 tegra234-flash-helper.sh ${TEGRA234_35_4_1_DIR}/bootloader/tegra234-flash-helper && \
    install -m 0755 tegra194-flash-helper.sh ${TEGRA186_35_4_1_DIR}/bootloader/tegra194-flash-helper && \
    install -m 0755 tegra-signimage-helper.sh ${TEGRA234_35_4_1_DIR}/tegra-signimage-helper && \
    install -m 0755 tegra-signimage-helper.sh ${TEGRA186_35_4_1_DIR}/tegra-signimage-helper

RUN patch -p1 --directory=${TEGRA234_35_4_1_DIR} < meta-tegra-kirkstone/recipes-bsp/tegra-binaries/files/0013-Fix-location-of-bsp_version-file-in-l4t_bup_gen.func.patch
RUN patch -p1 --directory=${TEGRA234_35_4_1_DIR} < meta-tegra-kirkstone/recipes-bsp/tegra-binaries/files/0014-odmsign.func-fix-ODMDATA-and-overlay-DTB-handling-fo.patch
RUN patch -p1 --directory=${TEGRA234_35_4_1_DIR} < meta-tegra-kirkstone/recipes-bsp/tegra-binaries/files/0016-Update-tegraflash_impl_t234.py.patch
RUN patch -p1 --directory=${TEGRA186_35_4_1_DIR} < meta-tegra-kirkstone/recipes-bsp/tegra-binaries/files/0013-Fix-location-of-bsp_version-file-in-l4t_bup_gen.func.patch
RUN patch -p1 --directory=${TEGRA186_35_4_1_DIR} < meta-tegra-kirkstone/recipes-bsp/tegra-binaries/files/0014-odmsign.func-fix-ODMDATA-and-overlay-DTB-handling-fo.patch
